### ISSUE TITLE
REQ_ATTACK AND CFB NOT WORK | KNOW !HTTP_REQ AND !HTTP_CFB NOT ATTACK SOME DSTAT

### ISSUE THREAD

**Issue by Hex1629** [NixWasHere/NebulaC2#33]
HEY I TEST TO HIT MY DSTAT WITH !HTTP_REQ BUT CAN'T HIT | 3/4/2023 

USE THIS COMMAND  !http_req https://dstat-ru-l7-3.24etaathng.repl.co/attack/ 443 50

REQ_ATTACK | LINE 1034 |  ip + ":" + port  | BUG |  CAN'T HIT SOME DSTAT 

AND CFB | LINE 1018 |  url = url + ":" + port  | BUG |  CAN'T HIT SOME DSTAT 

EXAMPLE LOGS -->

https://dstat-ru-l7-3.24etaathng.repl.co/attack/:443

https://layer7-dstat-1.termuxnoname.repl.co/dstat:443

**Comment by anonsecbotnetstudent123** [comment]
Repl Unavailable
This Repl is really popular! Try again soon.
[Go to Replit](https://replit.com/)
[Learn more about hosting on Replit](https://replit.com/site/hosting)

**Comment by NixWasHere** [comment]
I need better method.. I will fix asap.

**Comment by Hex1629** [comment]
ok thanks you
