### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Z3U3x** [NixWasHere/NebulaC2#36]
How can I have more bots?

**Comment by localuser-isback** [comment]
Idk VPS servers, buying bots from shops (dont ask where to get them i dont know), would not recommend infecting real PC's unless you like committing felonys :)

**Comment by DEVXapollo** [comment]
> Idk VPS servers, buying bots from shops (dont ask where to get them i dont know), would not recommend infecting real PC's unless you like committing felonys :)

buying bots could also be considered a felony depending on what you do with them. Since this C2 is mainly for DDOS i recommend just using Arduinos or VPS Servers :)

**Comment by localuser-isback** [comment]
> > Idk VPS servers, buying bots from shops (dont ask where to get them i dont know), would not recommend infecting real PC's unless you like committing felonys :)
> 
> buying bots could also be considered a felony depending on what you do with them. Since this C2 is mainly for DDOS i recommend just using Arduinos or VPS Servers :)

Yeah ofc, just dont be stupid with it basiclly lol
