### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by rishielol** [NixWasHere/NebulaC2#37]
When i Load main.py it says Succesfully Screened any Fixes?

**Comment by localuser-isback** [comment]
> When i Load main.py it says Succesfully Screened any Fixes?

That means its working lol, go to putty & set your mode to telnet & IP to 127.0.0.1 and port to 6667 (assuming this is on localhost)

**Comment by Z3U3x** [comment]
it seems layer7 is not working, i don't see the incoming request lol

**Comment by localuser-isback** [comment]
> it seems layer7 is not working, i don't see the incoming request lol

yeah it kida sucks tbh it needs a full rewrite

**Comment by NixWasHere** [comment]
I am working on NebulaC2 v2 where there will be many fixes.
