### ISSUE TITLE
Could've given wodx a little bit of credit, no?

### ISSUE THREAD

**Issue by iloveyumyumshrimpnoodles** [NixWasHere/NebulaC2#39]
Seeing as you based your project of [this](https://github.com/wodxgod/PYbot).
Not calling you a skiddie or anything, just wondering why you didn't give him some credit?

**Comment by NixWasHere** [comment]
Thanks, almost forgot about that!

**Comment by iloveyumyumshrimpnoodles** [comment]
cheers
